# Generated by Django 6.0.5 on 2026-05-30 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sticker_orders", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stickerorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sticker_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sticker_orders",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="stickerorder",
            index=models.Index(
                fields=["user", "status"], name="sticker_ord_user_id_6eba8e_idx"
            ),
        ),
    ]
