# Generated by Django 6.0.5 on 2026-05-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sticker_orders", "0002_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stickerorder",
            name="delivery_city",
        ),
        migrations.RemoveField(
            model_name="stickerorder",
            name="delivery_phone",
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="estimated_delivery_days",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="governorate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="id_back_photo",
            field=models.ImageField(blank=True, null=True, upload_to="sticker_docs/"),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="id_front_photo",
            field=models.ImageField(blank=True, null=True, upload_to="sticker_docs/"),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="license_photo",
            field=models.ImageField(blank=True, null=True, upload_to="sticker_docs/"),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="national_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="plate_letters",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="plate_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="plate_numbers",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="shipping_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="vehicle_brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="stickerorder",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sticker_orders",
                to="vehicles.vehicle",
            ),
        ),
    ]
