# Generated by Django 6.0.5 on 2026-05-31 21:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sticker_orders", "0003_remove_stickerorder_delivery_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stickerorder",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="id_back_photo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="id_front_photo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="license_photo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
