# Generated by Django 6.0.5 on 2026-05-31 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sticker_orders", "0004_alter_stickerorder_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stickerorder",
            name="quantity",
        ),
    ]
