# Generated by Django 6.0.5 on 2026-06-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sticker_orders", "0005_remove_stickerorder_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stickerorder",
            name="id_back_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="sticker_orders/id_back/"
            ),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="id_front_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="sticker_orders/id_front/"
            ),
        ),
        migrations.AlterField(
            model_name="stickerorder",
            name="license_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="sticker_orders/licenses/"
            ),
        ),
    ]
