# Generated by Django 6.0.5 on 2026-05-30 15:22

import uuid

from django.db import migrations, models

import apps.qr_codes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        db_index=True,
                        default=apps.qr_codes.models.generate_qr_hash,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("scan_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QR Code",
                "verbose_name_plural": "QR Codes",
                "db_table": "qr_codes",
            },
        ),
    ]
