# Generated by Django 6.0.5 on 2026-05-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qr_codes", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="vehicle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_code",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["code_hash", "is_active"], name="qr_codes_code_ha_06d5c6_idx"
            ),
        ),
    ]
