# Generated by Django 6.0.5 on 2026-05-30 15:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vehicle Location",
                "verbose_name_plural": "Vehicle Locations",
                "db_table": "vehicle_locations",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
