# Generated by Django 6.0.5 on 2026-05-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclelocation",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclelocation",
            index=models.Index(
                fields=["vehicle", "-recorded_at"],
                name="vehicle_loc_vehicle_ad6eaf_idx",
            ),
        ),
    ]
