# Generated by Django 6.0.5 on 2026-05-31 21:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_initial"),
        ("vehicles", "0002_alter_vehicle_photo_1_alter_vehicle_photo_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_sessions",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Session",
                "verbose_name_plural": "Tracking Sessions",
                "db_table": "tracking_sessions",
            },
        ),
    ]
