# Generated by Django 6.0.5 on 2026-05-30 15:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("toyota", "Toyota"),
                            ("bmw", "BMW"),
                            ("mercedes", "Mercedes-Benz"),
                            ("hyundai", "Hyundai"),
                            ("kia", "Kia"),
                            ("honda", "Honda"),
                            ("nissan", "Nissan"),
                            ("ford", "Ford"),
                            ("chevrolet", "Chevrolet"),
                            ("volkswagen", "Volkswagen"),
                            ("peugeot", "Peugeot"),
                            ("renault", "Renault"),
                            ("fiat", "Fiat"),
                            ("lada", "Lada"),
                            ("mitsubishi", "Mitsubishi"),
                            ("suzuki", "Suzuki"),
                            ("mazda", "Mazda"),
                            ("subaru", "Subaru"),
                            ("jeep", "Jeep"),
                            ("land_rover", "Land Rover"),
                            ("range_rover", "Range Rover"),
                            ("audi", "Audi"),
                            ("porsche", "Porsche"),
                            ("lexus", "Lexus"),
                            ("infiniti", "Infiniti"),
                            ("acura", "Acura"),
                            ("volvo", "Volvo"),
                            ("skoda", "Skoda"),
                            ("seat", "SEAT"),
                            ("opel", "Opel"),
                            ("dacia", "Dacia"),
                            ("chery", "Chery"),
                            ("geely", "Geely"),
                            ("byd", "BYD"),
                            ("jac", "JAC"),
                            ("mg", "MG"),
                            ("haval", "Haval"),
                            ("dongfeng", "Dongfeng"),
                            ("jetour", "Jetour"),
                            ("zotye", "Zotye"),
                            ("gac", "GAC"),
                            ("baic", "BAIC"),
                            ("lifan", "Lifan"),
                            ("changan", "Changan"),
                            ("foton", "Foton"),
                            ("great_wall", "Great Wall"),
                            ("huanghai", "Huanghai"),
                            ("king_long", "King Long"),
                            ("yutong", "Yutong"),
                            ("hino", "Hino"),
                            ("tesla", "Tesla"),
                            ("cadillac", "Cadillac"),
                            ("dodge", "Dodge"),
                            ("ram", "RAM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("black", "Black"),
                            ("silver", "Silver"),
                            ("gray", "Gray"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("brown", "Brown"),
                            ("gold", "Gold"),
                            ("beige", "Beige"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "photo_1",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "photo_2",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "photo_3",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                ("show_phone", models.BooleanField(default=False)),
                ("allow_call", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_active"],
                        name="vehicles_owner_i_e065d5_idx",
                    ),
                    models.Index(
                        fields=["plate_number"], name="vehicles_plate_n_de64b1_idx"
                    ),
                ],
            },
        ),
    ]
