# Generated by Django 6.0.5 on 2026-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="photo_1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="photo_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="photo_3",
            field=models.TextField(blank=True, null=True),
        ),
    ]
