# Generated by Django 6.0.5 on 2026-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="show_phone_in_requests",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_plan_id",
            field=models.CharField(default="free", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_status",
            field=models.CharField(default="ACTIVE", max_length=20),
        ),
    ]
