# Generated by Django 6.0.5 on 2026-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_show_phone_in_requests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
