# Generated by Django 6.0.5 on 2026-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
