# Generated by Django 6.0.5 on 2026-06-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscription_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
