# Generated by Django 6.0.5 on 2026-05-30 15:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("move", "Move Please"),
                            ("emergency", "Emergency"),
                            ("ticket", "Traffic Ticket"),
                            ("accident", "Accident"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "media_url",
                    models.FileField(blank=True, null=True, upload_to="request_media/"),
                ),
                (
                    "scanner_device_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("scanner_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("scanner_location", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
                "db_table": "requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
