# Generated by Django 6.0.5 on 2026-05-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requests", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["vehicle", "status", "-created_at"],
                name="requests_vehicle_12181f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["type", "status"], name="requests_type_cb8a94_idx"
            ),
        ),
    ]
