# Generated by Django 6.0.5 on 2026-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
    ]
